### ISSUE TITLE
Code is showing on the USB Webcam description

### ISSUE THREAD

**Issue by Frijol** [tessel/tessel.io#119]
As reported by @andy5995 in https://github.com/tessel/tessel.io/issues/116#issuecomment-334414771:

>I noticed the code is showing on the web page:
>
>Should be `<a title='Linux UVC driver and tools' href='http://www.ideasonboard.org/uvc/'>UVC-compatible</a>`,
>
>I've examined it and don't see a problem. The only difference between that link and the other links on the page is my addition of the title attribute.
>
>I'll fix this... if you tell me what the problem is! ;)

**Comment by Jeff-Duke** [comment]
I opened PR #126 for this, happy Hacktoberfest!
