### ISSUE TITLE
The website tessel.io is no longer working

### ISSUE THREAD

**Issue by strawherotk** [tessel/tessel.io#122]
Hello Team,

I've just tried to access [https://tessel.io/](https://tessel.io/) but it responds nothing.
It loaded a long time but end up showing nothing.
Are we having any problem?

Thanks.

**Comment by HipsterBrown** [comment]
Hi @strawherotk,

Thanks for making an issue. 👍

 I've posted an update about that on the [Tessel project twitter](https://twitter.com/tesselproject). https://www.tessel.io works right now and I'm still trying to get https://tessel.io to resolve. 

https://twitter.com/tesselproject/status/1004855337290215426

I'll keep this issue open until https://tessel.io is fixed.

**Comment by Frijol** [comment]
It's fixed!
