### ISSUE TITLE
Keen requests update

### ISSUE THREAD

**Issue by Frijol** [tessel/tessel.io#123]
Keen requests update of our listing of them:

> Could you remove the IO from our name, and change our location to San Antonio, TX?

**Comment by Frijol** [comment]
I found 
![screen shot 2018-07-02 at 10 32 01 am](https://user-images.githubusercontent.com/454690/42177979-8a390eec-7de3-11e8-8165-10448dbe168b.png)

but it doesn't have a location reference, so have requested clarification, maybe we refer to them somewhere else on the site?

**Comment by Frijol** [comment]
Clarified instruction: Replace the logo for Keen with this logo:

![unnamed](https://user-images.githubusercontent.com/454690/42390855-382969b8-8102-11e8-8d06-978f61a981bd.png)

(image is hosted at `https://s3.amazonaws.com/technicalmachine-assets/launch/partners/Keen.png`)

And change reference name to Keen instead of Keen IO (but keep the same URL).

The modification should take place in this file: https://github.com/tessel/tessel.io/blob/master/data.json

**Comment by Frijol** [comment]
It's displaying weirdly:

![unnamed](https://user-images.githubusercontent.com/454690/42981235-a1c0c116-8b87-11e8-81e5-d59fcbf0a0cc.png)

**Comment by Jeff-Duke** [comment]
I was poking around for `Hacktoberfest` issues to address.  This seems like it's resolved.  I checked in Chrome, Firefox and Safari and the logo is appearing as I _believe_ it should:
<img width="1341" alt="screen shot 2018-10-01 at 1 44 14 pm" src="https://user-images.githubusercontent.com/17116730/46305791-65405200-c580-11e8-8ef2-76da634155c0.png">

@Frijol Can this be closed or are there still changes to be made?

**Comment by Frijol** [comment]
Oh, yes, thanks for catching this! I resolved while traveling, so forgot to close the issue :)
