### ISSUE TITLE
Add a 404 page

### ISSUE THREAD

**Issue by Frijol** [tessel/tessel.io#16]
![screen shot 2015-10-18 at 5 17 12 pm](https://cloud.githubusercontent.com/assets/454690/10566692/2218942c-75bc-11e5-9035-65bc0defbdfe.png)

we can use this one

![screen shot 2015-10-18 at 5 17 26 pm](https://cloud.githubusercontent.com/assets/454690/10566693/28514d5c-75bc-11e5-9370-8cedd605c7ac.png)

Go to tessel.io/thanks to get the assets, add an Express 404 page. Email from Thanks page should be updated to `team@tessel.io`

**Comment by roboflank** [comment]
+1

**Comment by Frijol** [comment]
@denzelwamburu PR's welcome!
