### ISSUE TITLE
homepage tells you to install `tessel` not `t2-cli`

### ISSUE THREAD

**Issue by Frijol** [tessel/tessel.io#53]
![screen shot 2016-02-24 at 9 30 37 pm](https://cloud.githubusercontent.com/assets/454690/13310936/3e85c826-db3f-11e5-85c0-e7eeaa4eba45.png)

@rwaldron @johnnyman727 I think we still didn't come to a resolution on whether we want `tessel` and `t2-cli` to merge or otherwise change?

Anyway this should be `t2-cli` on the website in the meanwhile

**Comment by johnnyman727** [comment]
No, we haven't come to a resolution yet. I'd still love to switch all calls to `t2` to `tessel` in our CLI even if that means basically replacing all the code and making a major semver bump.
