### ISSUE TITLE
Changes to main page to guide more toward open source

### ISSUE THREAD

**Issue by Frijol** [tessel/tessel.io#6]
Paraphrasing a long thread in https://github.com/technicalmachine/technical-io/issues/325
- [ ] Add "Tessel is created by volunteer contributors just like you. [Get involved](//tessel.io/project)!" to the open source section of the page
- [ ] Make it clear what there is to do, what is being worked on, and what still needs to be done

Design ideas & discussion welcome

**Comment by ta11ey** [comment]
I dunno if you guys know, but the main tessel.io site has been down for about a week now and I can't access through any of my devices. Possibly there was an update to a new site that I haven't heard about, or under construction?

**Comment by Frijol** [comment]
closing in favor of https://github.com/tessel/tessel.io/issues/102
