### ISSUE TITLE
Get rid of the resellers page

### ISSUE THREAD

**Issue by Frijol** [tessel/tessel.io#67]
https://tessel.io/resellers
whoops, this isn't real anymore.

It's a link in the bottom nav bar, too.

**Comment by Frijol** [comment]
Would it be better to remove this page, update content, or have it redirect to https://www.seeedstudio.com/depot/index.php?main_page=distributors?

**Comment by Frijol** [comment]
cc @rwaldron @johnnyman727 @tcr for opinions please.

**Comment by johnnyman727** [comment]
I think we should instead have a URL or email address that someone can get in touch with. Reselling is still an option and good for the ecosystem.
